[package]
name = "captur"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
Walrus = { git = "https://github.com/MystenLabs/walrus.git", rev = "main", subdir = "testnet-contracts/walrus" }
token = { local = "../token"}

[addresses]
captur = "0x0"

